### PR TITLE
Refactor proofreading gameplay and general code cleanup

### PR DESCRIPTION
**Pull request by kriskelly**
I think we can merge this into `develop` because the app seems to be working properly. I deleted a bunch of dead code and extracted a few services / models out of the proofreading play controller, which was huge. @wlaurance Let me know what you think.

### CODE REVIEW

**Comment by kriskelly** [comment]
I can't figure out why JSHint is failing on Travis but passing locally. Maybe they updated JSHint on the Travis VMs?

**Comment by wlaurance** [comment]
Yeah that looks strange.

```
   src/scripts/services/rule.js
     44 |      var d = $q.defer();
                   ^ 'd' was used before it was defined.
```

This one for example. `d` is being declared?

**Comment by wlaurance** [comment]
I'm rebuilding node modules fresh like travis does and see if those same failures occur locally

**Comment by wlaurance** [comment]
OK the failures do occur locally.

**Comment by wlaurance** [comment]
@kriskelly The way https://github.com/empirical-org/Quill-Grammar/blob/8e8814b623c03518b6a7eba6f0441b00a09e03c5/src/scripts/services/auth/firebase.js#L32-L48 is written I don't think we can make jscs happy because the way the functions reference each other.

**Comment by wlaurance** [comment]
@kriskelly I made some changes above. This should pass ci. Let me know what you think and we can merge this PR.

**Comment by wlaurance** [comment]
This also raises the issue of not having our dependencies locked down enough. Do we need to think about a shrinkwrap file?

**Comment by kriskelly** [comment]
I was kind of under the impression that checking in node_modules/ was a thing that people did to avoid this sort of problem. We're doing that with Bower anyway so maybe that's the easiest solution.

**Comment by wlaurance** [comment]
Yeah we could do that to avoid issues like this. One problem, is we have compiled modules which don't save nicely.

This could be on a different thread for discussion.

With regards to this PR, :+1: let's merge.

**Pull request merged**
