### PR TITLE
Marcello oauth2

### PR DESCRIPTION
**Pull request by marcellosachs**
This was originally PR #97, there are comments there regarding how to improve the code on my branch before merging. (Created a new PR to change the target branch of the PR)

### CODE REVIEW

**Comment by marcellosachs** [comment]
@kriskelly I'm down to have the controllers compute the score and pass that to finalize service, there are only 2 issues with that : 
1. The score for the passage proofreading section could not be completely computed in the passage proofreading controller. This is because the final score is not simply the average of the score in passage proofreading and the score in sw, it is (num correct in passage proofreading + num correct in sw) / (num entries in passage proofreading + num entries in sw).
The most that the passage proofreading controller could do in terms of pre-processing is determine 'num correct in passage proofreading' and 'num entries in passage proofreading'
2. Given 1, there are two options for where the results from passage proofreading and sentence writing could be combined into a score - in the sentences controller or in the finalize service. I prefer having it be in the finalize service because then we arent as locked in to the fact that the sw exercises follow the passage proofreading exercises. Along that line or perhaps in other words - if we can't put logic related to passage proofreading in the passage proofreading controller, would prefer to put it in some abstract service rather than another controller.

What do you think of this pattern : 
Have the passage proofreading controller compute 'num correct' and 'num total entries', and store them in local storage. The sentence controller does the same for the sw exercises. The sentence controller then (still) calls finalize(sessionId, passageId). Finalize calls calculatePercentage, which involves much less logic because the 'num correct' and 'num total entries' have already been computed.

**Comment by marcellosachs** [comment]
@kriskelly I'm down to have the controllers compute the score and pass that to finalize service, there are only 2 issues with that : 
1. The score for the passage proofreading section could not be completely computed in the passage proofreading controller. This is because the final score is not simply the average of the score in passage proofreading and the score in sw, it is (num correct in passage proofreading + num correct in sw) / (num entries in passage proofreading + num entries in sw).
The most that the passage proofreading controller could do in terms of pre-processing is determine 'num correct in passage proofreading' and 'num entries in passage proofreading'
2. Given 1, there are two options for where the results from passage proofreading and sentence writing could be combined into a score - in the sentences controller or in the finalize service. I prefer having it be in the finalize service because then we arent as locked in to the fact that the sw exercises follow the passage proofreading exercises. Along that line or perhaps in other words - if we can't put logic related to passage proofreading in the passage proofreading controller, would prefer to put it in some abstract service rather than another controller.

What do you think of this pattern : 
Have the passage proofreading controller compute 'num correct' and 'num total entries', and store them in local storage. The sentence controller does the same for the sw exercises. The sentence controller then (still) calls finalize(sessionId, passageId). Finalize calls calculatePercentage, which involves much less logic because the 'num correct' and 'num total entries' have already been computed.

**Comment by kriskelly** [comment]
@marcellosachs I think given that the computation is a bit more involved than I originally thought, it's fine to keep the calculation in that 'calculate percentage' service and then call it from within finalize.

**Comment by marcellosachs** [comment]
@kriskelly ok cool

**Comment by kriskelly** [comment]
@marcellosachs Travis still fails for this PR, but if you can fix the build then it's probably good to go.

**Pull request merged**
