### PR TITLE
Include Passage Proofreading results in the calculation of a percentage to send back to the LMS

### PR DESCRIPTION
**Pull request by marcellosachs**
I imagine there might be a more elegant way to do this. For example, once we have recorded concept_ids (from concept level 0) in the passages, we can record the passage proofreading results as ConceptTagResults, just as the sentence writing results are recorded. If this is done, then determining the percentage would be a simpler process (just crunching the ConceptTagResults instead of two different arrays with elements of different structures). 

In the interest of shipping, however, I think this implementation should be adequate.

### CODE REVIEW

**Comment by kriskelly** [comment]
So a few pieces of feedback about this:

- the js file in documentation/ should probably be a markdown file, it's not valid JS. 
- a more elegant solution would be to calculate the score in the controllers and pass it to `finalize` as a 2nd argument, e.g. something like `finalize(sessionId, score)`. That way you could separate the percentage calculation into 2 services and you don't have all that switching logic all over the place, no localStorage dependency in the finalize service, etc. etc.

**Comment by kriskelly** [comment]
Also the Travis build failed due to linting errors:

https://travis-ci.org/empirical-org/Quill-Grammar/builds/71152264

**Comment by marcellosachs** [comment]
Ok cool. In the future will be running 'npm run lint' instead of 'gulp lint' given the inconsistencies between gulp and grunt. 

Thanks for the feedback on the design, should be able to refine this before merging.

**Comment by wlaurance** [comment]
That works for me. In the near future, I'd like to leverage NPM more and more.

**Comment by marcellosachs** [comment]
```javascript
var f = function (arg1) {
  console.log('hi')
}
```

**Comment by marcellosachs** [comment]
@kriskelly I'm down to have the controllers compute the score and pass that to finalize service, there are only 2 issues with that : 
1. The score for the passage proofreading section could not be completely computed in the passage proofreading controller. This is because the final score is not simply the average of the score in passage proofreading and the score in sw, it is (num correct in passage proofreading + num correct in sw) / (num entries in passage proofreading + num entries in sw).
The most that the passage proofreading controller could do in terms of pre-processing is determine 'num correct in passage proofreading' and 'num entries in passage proofreading'
2. Given 1, there are two options for where the results from passage proofreading and sentence writing could be combined into a score - in the sentences controller or in the finalize service. I prefer having it be in the finalize service because then we arent as locked in to the fact that the sw exercises follow the passage proofreading exercises. Along that line or perhaps in other words - if we can't put logic related to passage proofreading in the passage proofreading controller, would prefer to put it in some abstract service rather than another controller.

What do you think of this pattern : 
Have the passage proofreading controller compute 'num correct' and 'num total entries', and store them in local storage. The sentence controller does the same for the sw exercises. The sentence controller then (still) calls finalize(sessionId, passageId). Finalize calls calculatePercentage, which involves much less logic because the 'num correct' and 'num total entries' have already been computed.

**Pull request closed without merging**
